# Generated by Django 5.1.2 on 2024-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Westlands', 'Westlands'), ('Kasarani', 'Kasarani'), ('Embakasi', 'Embakasi'), ('Langata', 'Langata')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
