# Generated by Django 5.1.2 on 2024-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetApp', '0002_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
